import AsyncStorage from '@react-native-async-storage/async-storage'

AsyncStorage.setItem('email','');

const songs = [
    {
      title: "death bed",
      artist: "Powfu",
      artwork: require("../images/pic5.jpg"),
      url: "https://samplesongs.netlify.app/Death%20Bed.mp3",
      id: "1",
      language: "English",
    },
    {
      title: "Bad Liar",
      artist: "Imagine Dragons",
      artwork: require("../images/pic6.jpg"),
      url: "https://samplesongs.netlify.app/Bad%20Liar.mp3",
      id: "2",
      language: "English",
    },
    {
      title: "Faded",
      artist: "Alan Walker",
      artwork: require("../images/pic7.jpg"),
      url: "https://samplesongs.netlify.app/Faded.mp3",
      id: "3",
      language: "English",
    },
    {
      title: "Hate Me",
      artist: "Ellie Goulding",
      artwork: require("../images/pic8.jpg"),
      url: "https://samplesongs.netlify.app/Hate%20Me.mp3",
      id: "4",
      language: "English",
    },
    {
      title: "Solo",
      artist: "Clean Bandit",
      artwork: require("../images/pic9.jpg"),
      url: "https://samplesongs.netlify.app/Solo.mp3",
      id: "5",
      language: "English",
    },
    {
      title: "Without Me",
      artist: "Halsey",
      artwork: require("../images/pic15.jpg"),
      url: "https://samplesongs.netlify.app/Without%20Me.mp3",
      id: "6",
      language: "English",
    },
    {
      title: "Closer",
      artist: "The Chainsmokers",
      artwork: require("../images/pic7.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Closer.mp3?raw=true",
      id: "7",
      language: "English",
    },
    {
      title: "Don't Start Now",
      artist: "Dua Lipa",
      artwork: require("../images/pic10.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Dont_Start_Now.mp3?raw=true",
      id: "8",
      language: "English",
    },
    {
      title: "Dynamite",
      artist: "BTS",
      artwork: require("../images/pic16.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Dynamite.mp3?raw=true",
      id: "9",
      language: "English",
    },
    {
      title: "My Universe",
      artist: "Coldplay X BTS",
      artwork: require("../images/pic17.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/My%20Universe.mp3?raw=true",
      id: "10",
      language: "English",
    },
    {
      title: "New Rules",
      artist: "Dua Lipa",
      artwork: require("../images/pic18.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/New%20Rules.mp3?raw=true",
      id: "11",
      language: "English",
    },
    {
      title: "Perfect",
      artist: "Ed Sheeran",
      artwork: require("../images/pic19.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Perfect.mp3?raw=true",
      id: "12",
      language: "English",
    },
    {
      title: "Photograph",
      artist: "Ed Sheeran",
      artwork: require("../images/pic20.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Photograph.mp3?raw=true",
      id: "13",
      language: "English",
    },
    {
      title: "Shape Of You",
      artist: "Ed Sheeran",
      artwork: require("../images/pic21.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Shape%20Of%20You.mp3?raw=true",
      id: "14",
      language: "English",
    },
    {
      title: "Badri Ki Dulhania",
      artist: "Monali Thakur, Dev Negi, Ikka Singh, Neha Kakkar",
      artwork: require("../images/pic22.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Badri%20Ki%20Dulhania.mp3?raw=true",
      id: "15",
      language: "Hindi",
    },
    {
      title: "Desi Girl",
      artist: "Sunidhi Chauhan, Shankar Mahadevan",
      artwork: require("../images/pic23.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Desi%20Girl.mp3?raw=true",
      id: "16",
      language: "Hindi",
    },
    {
      title: "Gerua",
      artist: "Antara Mitra, Pritam Chakraborty, Arijit Singh",
      artwork: require("../images/pic24.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Gerua.mp3?raw=true",
      id: "17",
      language: "Hindi",
    },
    {
      title: "Humsafar",
      artist: "Akhil Sachdeva, Mansheel Gujral",
      artwork: require("../images/pic25.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Humsafar.mp3?raw=true",
      id: "18",
      language: "Hindi",
    },
    {
      title: "India Walle",
      artist: "Shankar Mahadevan, Neeti Mohan, Vishal Dadlani, KK",
      artwork: require("../images/pic26.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/India%20Waale.mp3?raw=true",
      id: "19",
      language: "Hindi",
    },
    {
      title: "Jai Jai Shivshankar",
      artist: "Vishal Dadlani",
      artwork: require("../images/pic27.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Jai%20Jai%20Shivshankar.mp3?raw=true",
      id: "20",
      language: "Hindi",
    },
    {
      title: "Kamli",
      artist: "Sunidhi Chauhan",
      artwork: require("../images/pic28.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Kamli.mp3?raw=true",
      id: "21",
      language: "Hindi",
    },
    {
      title: "Kusu Kusu",
      artist: "Zahrah S Khan, Dev Negi",
      artwork: require("../images/pic29.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Kusu%20Kusu.mp3?raw=true",
      id: "22",
      language: "Hindi",
    },
    {
      title: "Najaa",
      artist: "Pav Dharia, Nikhita Gandhi, Tanishk Bagchi",
      artwork: require("../images/pic30.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Najaa.mp3?raw=true",
      id: "23",
      language: "Hindi",
    },
    {
      title: "Paniyo Sa",
      artist: "Atif Aslam, Tulsi Kumar",
      artwork: require("../images/pic31.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/PANIYON%20SA.mp3?raw=true",
      id: "24",
      language: "Hindi",
    },
    {
      title: "Subhanallah",
      artist: "Sreerama Chandra, Shilpa Rao",
      artwork: require("../images/pic32.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Subhanallah.mp3?raw=true",
      id: "25",
      language: "Hindi",
    },
    {
      title: "Sun Saathiya",
      artist: "Divya Kumar, Priya Saraiya",
      artwork: require("../images/pic33.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/Sun%20Saathiya.mp3?raw=true",
      id: "26",
      language: "Hindi",
    },
    {
      title: "The Disco Song",
      artist: "Nazia Hassan, Benny Dayal, Sunidhi Chauhan",
      artwork: require("../images/pic34.jpg"),
      url: "https://github.com/Priyanshi-S/Music_App/blob/main/src/songs/The%20Disco%20Song.mp3?raw=true",
      id: "27",
      language: "Hindi",
    },
  ]
  export default songs;
